name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: rifairizqi3/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_9a1f5bd1-2084-42ee-8fda-812a7e48d7c6 }}
          GH_TOKEN: ${{ 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 }}
