name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: rifairizqi3/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_31ac6d1b-08a8-43c5-b3f3-4f1b950d83e1 }}
          GH_TOKEN: ${{ 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 }}
